//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class График_работы
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public График_работы()
        {
            this.Сведения_о_сотрудниках = new HashSet<Сведения_о_сотрудниках>();
        }
    
        public int Id_графика { get; set; }
        public string Понедельник { get; set; }
        public string Вторник { get; set; }
        public string Среда { get; set; }
        public string Четверг { get; set; }
        public string Пятница { get; set; }
        public string Суббота { get; set; }
        public string Воскресенье { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Сведения_о_сотрудниках> Сведения_о_сотрудниках { get; set; }
    }
}
