//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Должности
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Должности()
        {
            this.Сведения_о_сотрудниках = new HashSet<Сведения_о_сотрудниках>();
            this.СотрудникиБригад = new HashSet<СотрудникиБригад>();
        }
    
        public int Id_должности { get; set; }
        public string Наименование_должности { get; set; }
        public Nullable<int> Id_услуги { get; set; }
    
        public virtual Услуги Услуги { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Сведения_о_сотрудниках> Сведения_о_сотрудниках { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<СотрудникиБригад> СотрудникиБригад { get; set; }
    }
}
