//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заявки
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Заявки()
        {
            this.Работа_бригад_за_месяц = new HashSet<Работа_бригад_за_месяц>();
        }
    
        public int Id_заявки { get; set; }
        public string Фамилия_клиента { get; set; }
        public string Имя_клиента { get; set; }
        public string Отчество_клиента { get; set; }
        public string Телефон { get; set; }
        public string e_mail { get; set; }
        public string Наименование_услуги { get; set; }
        public string Сроки_исследования__начало_конец_ { get; set; }
        public string Координаты_объекта_исследования { get; set; }
        public Nullable<decimal> Итогодая_цена { get; set; }
        public Nullable<System.DateTime> Дата_добавления_заявки { get; set; }
        public string Заявка_выполнена___не_выполнена__да_нет_ { get; set; }
        public Nullable<System.DateTime> Дата_выполнения_заявки { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Работа_бригад_за_месяц> Работа_бригад_за_месяц { get; set; }
    }
}
