//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Работа_бригад_за_месяц
    {
        public int Id_сотрудника { get; set; }
        public Nullable<int> Id_заявки { get; set; }
        public Nullable<int> Id_бригады { get; set; }
        public string Время_на_выполнение_заявки { get; set; }
        public Nullable<System.DateTime> Дата_выполнения_заявки { get; set; }
    
        public virtual Бригады Бригады { get; set; }
        public virtual Заявки Заявки { get; set; }
    }
}
