//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Сведения_о_сотрудниках
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Сведения_о_сотрудниках()
        {
            this.СотрудникиБригад = new HashSet<СотрудникиБригад>();
        }
    
        public int Id_сотрудника { get; set; }
        public string Фамилия_сотрудника { get; set; }
        public string Имя_сотрудника { get; set; }
        public string Отчество_сотрудника { get; set; }
        public string Телефон { get; set; }
        public Nullable<System.DateTime> Дата_рождения { get; set; }
        public string Адрес_проживания { get; set; }
        public Nullable<int> Id_графика { get; set; }
        public Nullable<int> Id_должности { get; set; }
    
        public virtual График_работы График_работы { get; set; }
        public virtual Должности Должности { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<СотрудникиБригад> СотрудникиБригад { get; set; }
    }
}
