//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class СотрудникиБригад
    {
        public int Id_сотрудника_бригады { get; set; }
        public Nullable<int> Id_сотрудника { get; set; }
        public Nullable<int> Id_должности { get; set; }
        public Nullable<int> id_бригады { get; set; }
    
        public virtual Бригады Бригады { get; set; }
        public virtual Должности Должности { get; set; }
        public virtual Сведения_о_сотрудниках Сведения_о_сотрудниках { get; set; }
    }
}
